### ISSUE TITLE
Don't use text-encoding package (certainly not in browsers)

### ISSUE THREAD

**Issue by sachaw** [emeraldpay/hashicon#34]
I love this package, however I am using this in a very space constrained application, and the inclusion of the `text-encoding` package adds 615kb to my uncompressed bundle size (single largest dep by far). It's also deprecated.

I'd be happy to help get this working.

**Comment by oori** [comment]
@splix Why was TextEncoder added?
https://github.com/emeraldpay/hashicon/commit/e386fb3da363c8b0ed9295eae251f62a8e995e31

**Comment by splix** [comment]
hm, I think it was part of something different, but ended up committing it. I don't think it's used.

@sachaw can you try to remove the dependency and see if that works for you? If yes, I'd appreciate a pull request.

**Comment by splix** [comment]
@sachaw published to NPM as v0.5.2
